const path = require('path');
const fs = require('fs');
const https = require('https');
const express = require('express');
const db = require('./db');

const PORT = process.env.PORT || 3003;
const DB_PATH = process.env.DB_PATH || path.join(__dirname, '..', 'data', 'calories.db');
const STATIC_DIR = path.join(__dirname, '..', '..', 'frontend', 'dist');

// Browsers only expose camera access (getUserMedia, used for the barcode
// scanner) on "secure contexts" - HTTPS or localhost. Since this app is
// reached over plain http://<hostname>:PORT on the LAN, we also serve HTTPS
// with a self-signed certificate (generated by setup.sh) whenever one is
// available, so the barcode scanner works from phones on the network.
const HTTPS_PORT = process.env.HTTPS_PORT || 3443;
const TLS_CERT_PATH = process.env.TLS_CERT_PATH || path.join(path.dirname(DB_PATH), 'tls', 'cert.pem');
const TLS_KEY_PATH = process.env.TLS_KEY_PATH || path.join(path.dirname(DB_PATH), 'tls', 'key.pem');

async function main() {
  await db.initDb(DB_PATH);

  const app = express();
  app.use(express.json());

  app.use('/api/persons', require('./routes/persons'));
  app.use('/api/foods', require('./routes/foods'));
  app.use('/api/meals', require('./routes/meals'));
  app.use('/api/entries', require('./routes/entries'));
  app.use('/api/summary', require('./routes/summary'));
  app.use('/api/off-config', require('./routes/off-config'));

  // Serve the built frontend (production/Docker image); harmless if the dist
  // folder doesn't exist yet during local backend-only development.
  app.use(express.static(STATIC_DIR));
  app.get(/^\/(?!api).*/, (req, res, next) => {
    res.sendFile(path.join(STATIC_DIR, 'index.html'), (err) => {
      if (err) next();
    });
  });

  app.listen(PORT, () => {
    console.log(`calories backend listening on port ${PORT} (DB: ${DB_PATH})`);
  });

  if (fs.existsSync(TLS_CERT_PATH) && fs.existsSync(TLS_KEY_PATH)) {
    const options = {
      cert: fs.readFileSync(TLS_CERT_PATH),
      key: fs.readFileSync(TLS_KEY_PATH),
    };
    https.createServer(options, app).listen(HTTPS_PORT, () => {
      console.log(`calories backend also listening on HTTPS port ${HTTPS_PORT} (self-signed cert)`);
    });
  } else {
    console.log(
      `No TLS certificate found at ${TLS_CERT_PATH} - HTTPS disabled (camera/barcode scan needs HTTPS or localhost).`
    );
  }
}

main().catch((err) => {
  console.error('Failed to start server', err);
  process.exit(1);
});

